"""ReportLab PDF generation for CBAM reports."""
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from io import BytesIO
from datetime import datetime


PRIMARY_GREEN = colors.HexColor("#1B5E20")
ACCENT_TEAL = colors.HexColor("#00897B")
LIGHT_GREEN = colors.HexColor("#F1F8F2")


def generate_cbam_report(result_id: str, company_info: dict, installation_info: dict) -> bytes:
    """Generate a professional CBAM compliance report PDF."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            rightMargin=2*cm, leftMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    header_style = ParagraphStyle("Header", parent=styles["Title"],
                                  textColor=PRIMARY_GREEN, fontSize=22, spaceAfter=6)
    story.append(Paragraph("CarbonCove", header_style))
    story.append(Paragraph("CBAM Compliance Report", styles["Heading2"]))
    story.append(Spacer(1, 0.5*cm))

    story.append(Paragraph(f"Company: {company_info.get('name', 'N/A')}", styles["Normal"]))
    story.append(Paragraph(f"Installation: {installation_info.get('name', 'N/A')}", styles["Normal"]))
    story.append(Paragraph(f"Report ID: {result_id}", styles["Normal"]))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%d %b %Y, %H:%M IST')}", styles["Normal"]))
    story.append(Spacer(1, 1*cm))

    data = [
        ["Metric", "Value"],
        ["Scope 1 Emissions", f"{installation_info.get('scope1_direct', 0):.3f} tCO₂"],
        ["Scope 2 Emissions", f"{installation_info.get('scope2_indirect', 0):.3f} tCO₂"],
        ["Total Embedded Emissions", f"{installation_info.get('total_embedded', 0):.3f} tCO₂"],
        ["Specific Emissions", f"{installation_info.get('specific_embedded', 0):.4f} tCO₂/tonne"],
        ["EU Default Value", f"{installation_info.get('eu_default_value', 0):.4f} tCO₂/tonne"],
        ["CBAM Cost (Actual)", f"₹{installation_info.get('cbam_cost_actual', 0):,.2f}"],
        ["CBAM Cost (EU Default)", f"₹{installation_info.get('cbam_cost_default', 0):,.2f}"],
        ["Savings vs Default", f"₹{installation_info.get('savings_vs_default', 0):,.2f}"],
    ]
    t = Table(data, colWidths=[9*cm, 8*cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY_GREEN),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [LIGHT_GREEN, colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(t)
    story.append(Spacer(1, 1*cm))

    footer_style = ParagraphStyle("Footer", parent=styles["Normal"],
                                  textColor=colors.grey, fontSize=8)
    story.append(Paragraph(
        "Generated by CarbonCove v1.0 | EU Reg 2023/1773 Compliant | "
        "This report is for compliance guidance purposes only.",
        footer_style
    ))

    doc.build(story)
    return buffer.getvalue()
